#Eureka server服务端⼝
server:
                  port: 8761
spring:
    application:
        # 应⽤名称，会在Eureka中作为服务的id标识（serviceId）
        name: idstaa-cloud-eureka-server
    profiles: IdstaaCloudEurekaServerA
eureka:
    instance:
        hostname: IdstaaCloudEurekaServerA
    client:
        service-url: # 客户端与EurekaServer交互的地址，如果是集群，也需要写其它Server的地址
          defaultZone: http://IdstaaCloudEurekaServerB:8762/eureka
        # ⾃⼰就是服务不需要注册⾃⼰
        register-with-eureka: true
        #⾃⼰就是服务不需要从Eureka Server获取服务信息,默认为true，置为false
        fetch-registry: true


